### ISSUE TITLE
JSON-Datapoint not usable in binding

### ISSUE THREAD

**Issue by oweitman** [ioBroker/ioBroker.vis#263]
is is not possibe to use a JSON-String in a binding operation if the JSON contains douple quotaition marks.

Example:
- Create Datapoint "javascript.0.json" type string and content: [{"a":1},{"a":2}]
-create a basic HTML widget and following binding in HTML-property: {a:javascript.0.json;console.debug(a)}

if you change the datapoint to [{'a':1},{'a':2}]

it works.
if you request json data from external services it is not easy to change all doupe quotation marks to singel quotation marks

a possible solution is to test the string for valid JSON-Data (this includes also number, false,true) as follows: 
1. Test for JSON-Data. if no Error you can add the string without quotation marks (true,false,JSON,numbers)
2 if the Test fails, add Data with quotaion marks. (strings)

```javascript
    try {
        if (JSON.parse(value));
        string += 'var ' + oids[t].operations[k].arg[a].name + ' = ' + value + ';';
    } catch(e) {
        string += 'var ' + oids[t].operations[k].arg[a].name + ' = "' + value + '";';
    }
```

affected code https://github.com/ioBroker/ioBroker.vis/blob/4eed0e941d5ca15fae89d3a72ee3cfd30b2b1774/www/js/vis.js#L2377

**Comment by gsicilia82** [comment]
In my case it's not possible to bin JSONs at all.

I have tested the following code, it's without try/catch. Maybe it's faster but you have to parse the binding in second step:

`string += 'var ' + oids[t].operations[k].arg[a].name + ' = ' + JSON.stringify(value) + ';';`

Binding Example: {a: json.state; JSON.parse(a)["key"]}

For me it doesn't matter. I like your solution, because parsing is not necessary. Unfortunately in both cases is not possible to bind Arrays.
I tested an if-statement with

```
if (typeof value === "object") {
         ..... insert value without quotes
} else {
         ..... insert value with quotes
}
```

But I got errors in browsers console "type of undefined etc."

@oweitman 
Maybe, if you make a pull request, they would merge your solution.

**Comment by oweitman** [comment]
@gsicilia82
your example only works for simple datatypes (bool,number,string,etc). 
if a JSON-string arrives you stringify it again. this leads to escaping quotation marks and this is wrong.
did you have an example of an array that didnt worked?

**Comment by gsicilia82** [comment]
@oweitman 
in my example, it works for JSONs when getting them from iobroker state. At least, they are parsable... The benefit with stringify is, that you neither need if/else nor try/catch.

Not one Array worked for me. It doesn't matter which one I tested. e.g.
objectState = ["a","b","c"]

`{a:objectState;a[0]}` shows "[" instead of "a". Because the Array is stored with quotes in `var a`; it's a String not an Array. This leads to show first char instead of first element.
