### ISSUE TITLE
Update of adapter does not preserve locallink value

### ISSUE THREAD

**Issue by nkleber78** [ioBroker/ioBroker.vis#319]
If the adapter is updated, it always changes the locallink value back to its default. This means after every update i need to set this value again. This should not happen. Is it possible to preserve the value during update process?

**Comment by Apollon77** [comment]
Why and to what you mondify the value? And how? Do you edit the object?

**Comment by nkleber78** [comment]
I need to modify this value because i have 2 url's one for vis/web and another for admin. Both URLs are served by port 443, no port forwarding for the special ports of iobroker. Therefore i modify the value in system.adapter.vis.0 to the needed locallink value of https://sub.domain.com

**Comment by Apollon77** [comment]
Then this would be a general feature request for the js-controler because all "field preserving during updates" is handled there. Right now "localLink" is none of the fields to be preserved because else we have no chance ever to fix a broken link there or change one.
This would need a discussion.

please open as Featrue Request in js.controller project. Thank you!
